const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Funko Pop Boruto",
      price: 500,
      image: require("./images/img01.jpg"),
      category: "anime",
      // img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
      // img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },
    {
      id: 2,
      title: "Funko Pop Carrie",
      price: 300,
      image: require("./images/img02.jpg"),
      category: "cine",
      //  img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-Pine-Green/Images/Nike-Dunk-Low-Off-White-Pine-Green/Lv2/img",
      //  img2: ".jpg?auto=format,compress&q=90&updated_at=1606319825&w=1000",
      cantidad: 1,
    },
    {
      id: 3,
      title: "Funko Pop Chucky",
      price: 600,
      image: require("./images/img03.jpg"),
      category: "cine",
      // img1: "https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Lv2/img",
      // img2: ".jpg?auto=format,compress&q=90&updated_at=1606325289&w=1000",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Funko Pop Darth Maul",
      price: 650,
      image: require("./images/img04.jpg"),
      category: "Star-Wars",
      // img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      // img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 5,
      title: "Funko Pop Freddie Mercury",
      price: 900,
      image: require("./images/img05.jpg"),
      category: "music",
      //  img1: " https://stockx-360.imgix.net/Nike-Dunk-Low-SP-Kentucky/Images/Nike-Dunk-Low-SP-Kentucky/Lv2/img",
      //  img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
      cantidad: 1,
    },
    {
      id: 6,
      title: "Funko Pop Harry Potter",
      price: 750,
      image: require("./images/img06.jpg"),
      category: "cine",
      //   img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-University-Red/Images/Nike-Dunk-Low-Off-White-University-Red/Lv2/img",
      //  img2: ".jpg?auto=format,compress&q=90&updated_at=1606321824&w=1000",
      cantidad: 1,
    },
    {
      id: 7,
      title: "Funko Pop Obi-Wan Kenobi",
      price: 860,
      image: require("./images/img07.jpg"),
      category: "Star-Wars",
      //  img1: "https://stockx-360.imgix.net/Nike-Air-Max-2-Light-Atmos/Images/Nike-Air-Max-2-Light-Atmos/Lv2/img",
      //  img2: ".jpg?auto=format,compress&q=90&updated_at=1606320966&w=1000",
      cantidad: 1,
    },
    {
      id: 8,
      title: "Funko Pop Pikachu",
      price: 900,
      image: require("./images/img08.jpg"),
      category: "anime",
      //   img1: "https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Clot-Blue-Silk/Images/Nike-Air-Force-1-Low-Clot-Blue-Silk/Lv2/img",
      //   img2: ".jpg?auto=format,compress&q=90&updated_at=1606325265&w=1000",
      cantidad: 1,
    },
    {
      id: 9,
      title: "Funko Pop Rocky Balboa",
      price: 799,
      image: require("./images/img09.jpg"),
      category: "cine",
      //   img1: "https://stockx-360.imgix.net/Nike-Air-Max-90-OG-White-Particle-Grey-Volt/Images/Nike-Air-Max-90-OG-White-Particle-Grey-Volt/Lv2/img",
      //   img2: ".jpg?auto=format,compress&q=90&updated_at=1606323250&w=1000",
      cantidad: 1,
    },
    {
      id: 10,
      title: "Funko Pop Goku SSG",
      price: 1200,
      image: require("./images/img10.jpg"),
      category: "anime",
      //  img1: "https://stockx-360.imgix.net/Nike-Dunk-High-Black-Varsity-Maize/Images/Nike-Dunk-High-Black-Varsity-Maize/Lv2/img",
      //  img2: ".jpg?auto=format,compress&q=90&updated_at=1609445259&w=1000",
      cantidad: 1,
    },
    {
      id: 11,
      title: "Funko Pop Slash",
      price: 850,
      image: require("./images/img011.jpg"),
      category: "music",
      //   img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      //   img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 1,
    },
  ],
};

export default data;
